Repository webb-tools/relayer, pull requests merged in 2022-05, with the labels that each got.

#171 more negative tests
  tests/lib/substrateNodeBase.ts
  tests/package.json
  tests/test/substrate/anchorTransactionRelayer.test.ts
  tests/test/substrate/mixerTransactionRelayer.test.ts
  tests/yarn.lock
Labels: approved ✅

#172 evm vanchor leaves watcher #160
  src/config.rs
  src/events_watcher/anchor_watcher.rs
  src/events_watcher/evm/anchor_leaves_watcher.rs
  src/events_watcher/evm/anchor_watcher.rs
  src/events_watcher/evm/mod.rs
  src/events_watcher/evm/vanchor_leaves_watcher.rs
  src/events_watcher/mod.rs
  src/service.rs
  tests/lib/localTestnet.ts
  tests/lib/webbRelayer.ts
  tests/package.json
  tests/test/evm/evmTransactionRelayer.test.ts
  tests/test/evm/governorUpdates.test.ts
  tests/test/evm/vanchorTransactionRelayer.test.ts
  tests/test/proposals.test.ts
  tests/test/signatureBridge.test.ts
Labels: approved ✅

#178 Mocked Signing Backend Generalization
  Cargo.lock
  Cargo.toml
  src/events_watcher/governor_watcher.rs
  src/events_watcher/proposal_handler_watcher.rs
  src/events_watcher/proposal_signing_backend/mocked.rs
  src/service.rs
  src/store/mod.rs
  src/store/sled.rs
  tests/lib/localTestnet.ts
  tests/test/signatureBridge.test.ts
Labels: feature ➕

#179 Optional proposal signing backend #177
  src/config.rs
  src/service.rs
  tests/lib/localTestnet.ts
  tests/test/evm/SimpleTransactionRelayer.test.ts
Labels: approved ✅

#181 chore: remove old config and update readme
  README.md
  config/local-testnet/athena.toml
  config/local-testnet/hermes.toml
  config/local-testnet/main.toml
Labels: needs review 👓

#182 VAnchor Governance
  src/config.rs
  src/events_watcher/evm/mod.rs
  src/events_watcher/evm/vanchor_watcher.rs
  src/service.rs
  tests/lib/localTestnet.ts
  tests/lib/substrateNodeBase.ts
  tests/lib/webbRelayer.ts
  tests/test/evm/vanchorGovernance.test.ts
  tests/test/proposals.test.ts
  tests/test/signatureBridge.test.ts
  tests/test/substrate/mixerTransactionRelayer.test.ts
Labels: feature ➕, needs review 👓

#183 Improve the CI by using pre-built DKG Node
  .github/workflows/ci.yml
  tests/.mocharc.jsonc
  tests/test/evm/governorUpdates.test.ts
  tests/test/evm/vanchorGovernance.test.ts
  tests/test/proposals.test.ts
  tests/test/signatureBridge.test.ts
  tests/test/substrate/anchorTransactionRelayer.test.ts
  tests/test/substrate/mixerTransactionRelayer.test.ts
Labels: optimization ⚙️, wip 🚧
