Repository webb-tools/relayer, pull requests merged in 2022-08, with the labels that each got.

#217 substrate tx queue
  src/config.rs
  src/events_watcher/mod.rs
  src/events_watcher/substrate/signature_bridge_watcher.rs
  src/service.rs
  src/store/sled.rs
  src/tx_queue/evm/evm_tx_queue.rs
  src/tx_queue/evm/mod.rs
  src/tx_queue/mod.rs
  src/tx_queue/substrate/call_data.rs
  src/tx_queue/substrate/mod.rs
  src/tx_queue/substrate/substrate_tx_queue.rs
  tests/test/substrate/signatureBridgeVanchor.test.ts
Labels: feature ➕, needs changes 🔧, optimization ⚙️

#238 Rework Bridge Command Watchers
  config/development/cosmwasm-localnet/juno.toml
  config/development/cosmwasm-localnet/terra.toml
  config/development/dkg/athena-dkg.toml
  config/development/dkg/dkg-local.toml
  config/development/dkg/hermes-dkg.toml
  config/development/evm-localnet/athena.toml
  config/development/evm-localnet/demeter.toml
  config/development/evm-localnet/dkg.toml
  config/development/evm-localnet/hermes.toml
  config/exclusive-strategies/8sided-evm-bridge/arbitrum_test.toml
  config/exclusive-strategies/8sided-evm-bridge/goerli.toml
  config/exclusive-strategies/8sided-evm-bridge/kovan.toml
  config/exclusive-strategies/8sided-evm-bridge/moonbase.toml
  config/exclusive-strategies/8sided-evm-bridge/optimism_test.toml
  config/exclusive-strategies/8sided-evm-bridge/polygon_test.toml
  config/exclusive-strategies/8sided-evm-bridge/rinkeby.toml
  config/exclusive-strategies/8sided-evm-bridge/ropsten.toml
  src/config.rs
  src/events_watcher/dkg/proposal_handler_watcher.rs
  src/events_watcher/evm/vanchor_deposit_handler.rs
  src/events_watcher/mod.rs
  src/service.rs
  src/tx_queue/substrate/substrate_tx_queue.rs
  tests/lib/localTestnet.ts
  tests/lib/substrateNodeBase.ts
  tests/lib/webbRelayer.ts
  tests/test/evm/vanchorGovernance.test.ts
  tests/test/substrate/signatureBridgeVanchor.test.ts
Labels: needs review 👓, optimization ⚙️

#241 Prepare for Release v0.4.0
  .github/workflows/ci.yml
  .github/workflows/image-publish.yml
  .github/workflows/lints.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  README.md
  config/development/evm-localnet/dkg.toml
  src/config.rs
  src/context.rs
  src/events_watcher/dkg/governor_watcher.rs
  src/events_watcher/evm/mod.rs
  src/events_watcher/evm/signature_bridge_watcher.rs
  src/handler.rs
  src/proposal_signing_backend/dkg.rs
  src/proposal_signing_backend/mocked.rs
  src/store/sled.rs
  src/tx_queue/evm/evm_tx_queue.rs
  tests/lib/localTestnet.ts
  tests/lib/substrateNodeBase.ts
Labels: p1 🟠, testing 🛠️, needs review 👓, optimization ⚙️

#249 Webb Relayer as crate
  Cargo.toml
  examples/in_depth.rs
  src/config.rs
  src/context.rs
  src/error.rs
  src/events_watcher/mod.rs
  src/handler.rs
  src/lib.rs
  src/main.rs
  src/service.rs
  src/store/mod.rs
  src/store/sled.rs
  src/tx_queue/evm/evm_tx_queue.rs
  src/tx_queue/mod.rs
  src/tx_queue/substrate/call_data.rs
  src/tx_queue/substrate/mod.rs
  src/tx_relay/evm/mod.rs
  src/tx_relay/mod.rs
  src/tx_relay/substrate/mod.rs
  src/types/mod.rs
  src/types/private_key.rs
  src/types/rpc_url.rs
  src/types/suri.rs
Labels: p1 🟠, needs review 👓, optimization ⚙️

#247 Update webb_proposals and add dry run tests before executing transactions.
  Cargo.lock
  Cargo.toml
  src/events_watcher/evm/signature_bridge_watcher.rs
  src/events_watcher/evm/vanchor_deposit_handler.rs
  src/events_watcher/mod.rs
  src/events_watcher/substrate/signature_bridge_watcher.rs
  src/events_watcher/substrate/vanchor_watcher.rs
  src/service.rs
  src/store/mod.rs
  src/tx_queue/evm/evm_tx_queue.rs
  src/tx_queue/substrate/substrate_tx_queue.rs
  tests/lib/substrateWebbProposals.ts
  tests/lib/webbProposals.ts
  tests/test/evm/vanchorGovernance.test.ts
  tests/test/substrate/signatureBridgeVanchor.test.ts
Labels: needs review 👓

#252 Add the `cosmwasm` configuration into the `WebbRelayerConfig`
  Cargo.lock
  Cargo.toml
  config/development/cosmwasm-localnet/juno.toml
  config/development/cosmwasm-localnet/terra.toml
  src/config.rs
  src/types/cw_chain_id.rs
  src/types/mod.rs
  src/utils.rs
Labels: needs review 👓
