Repository webb-tools/relayer, pull requests merged in 2022-04, with the labels that each got.

#112 Signature Bridge Integration with Relayer and DKG
  .github/workflows/ci.yml
  src/config.rs
  src/events_watcher/anchor_watcher.rs
  src/events_watcher/mod.rs
  src/events_watcher/proposal_handler_watcher.rs
  src/events_watcher/signature_bridge_watcher.rs
  src/handler.rs
  src/probe.rs
  src/service.rs
  src/store/mod.rs
  src/store/sled.rs
  src/tx_queue.rs
  tests/.prettierrc.json
  tests/lib/ethHelperFunctions.ts
  tests/lib/localDkg.ts
  tests/lib/localProtocolSubstrate.ts
  tests/lib/localTestnet.ts
  tests/lib/substrateNodeBase.ts
  tests/lib/webbRelayer.ts
  tests/package.json
  tests/test/evmTransactionRelayer.test.ts
  tests/test/signatureBridge.test.ts
  tests/test/subTransactionRelayer.test.ts
  tests/yarn.lock
Labels: p2

#156 EVM Events Deduplication
  Cargo.lock
  Cargo.toml
  src/events_watcher/anchor_watcher.rs
  src/events_watcher/mod.rs
  src/store/mod.rs
  src/store/sled.rs
Labels: enhancement, p2

#153 Updates and additions for new Substrate tx_relayer handlers
  Cargo.lock
  Cargo.toml
  src/handler.rs
  src/tx_relay/evm/anchor.rs
  src/tx_relay/evm/mod.rs
  src/tx_relay/evm/vanchor.rs
  src/tx_relay/mod.rs
  src/tx_relay/substrate/anchor.rs
  src/tx_relay/substrate/mixer.rs
  src/tx_relay/substrate/mod.rs
  src/tx_relay/substrate/vanchor.rs
  tests/lib/webbRelayer.ts
  tests/test/substrate/anchorTransactionRelayer.test.ts
  tests/test/substrate/mixerTransactionRelayer.test.ts
Labels: needs review 👓, optimization ⚙️

#158 Substrate anchor relayer support
  src/tx_relay/evm/vanchor.rs
  tests/lib/webbRelayer.ts
  tests/test/substrate/anchorTransactionRelayer.test.ts
Labels: needs review 👓, task ✔️

#157 Listen to DKG PublicKey Changes and Update SignatureBridge Governor
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/events_watcher/governor_watcher.rs
  src/events_watcher/mod.rs
  src/events_watcher/signature_bridge_watcher.rs
  src/service.rs
  src/store/mod.rs
  tests/.mocharc.json
  tests/.mocharc.jsonc
  tests/lib/localDkg.ts
  tests/lib/sleep.ts
  tests/lib/substrateNodeBase.ts
  tests/lib/timeout.ts
  tests/lib/webbRelayer.ts
  tests/test/evmTransactionRelayer.test.ts
  tests/test/governorUpdates.test.ts
  tests/test/signatureBridge.test.ts
  tests/test/substrate/anchorTransactionRelayer.test.ts
  tests/test/substrate/mixerTransactionRelayer.test.ts
Labels: feature ➕, needs review 👓

#164 Salman substrate event watcher
  src/config.rs
  src/events_watcher/mod.rs
  src/events_watcher/substrate/anchor_leaves_watcher.rs
  src/events_watcher/substrate/mod.rs
  src/service.rs
  src/store/mod.rs
  tests/lib/localProtocolSubstrate.ts
  tests/lib/webbRelayer.ts
  tests/test/substrate/anchorTransactionRelayer.test.ts
  tests/test/substrate/mixerTransactionRelayer.test.ts
  tests/test/utils/ethAddressFromString.ts
Labels: needs review 👓

#167 Handle more proposal types
  src/events_watcher/proposal_handler_watcher.rs
  tests/lib/ethHelperFunctions.ts
  tests/lib/localDkg.ts
  tests/lib/webbProposals.ts
  tests/lib/webbRelayer.ts
  tests/package.json
  tests/test/evm/evmTransactionRelayer.test.ts
  tests/test/evm/governorUpdates.test.ts
  tests/test/proposals.test.ts
  tests/yarn.lock
Labels: feature ➕, needs review 👓
