Repository webb-tools/relayer, pull requests merged in 2023-05, with the labels that each got.

#492 Setup Development env using Nix and Flakes
  .envrc
  .gitignore
  flake.lock
  flake.nix
  rust-toolchain.toml
  tests/.envrc
Labels: dependencies

#493 fix: Add RetryClient to the EVM Providers
  crates/event-watcher-traits/src/evm/bridge_watcher.rs
  crates/event-watcher-traits/src/evm/event_watcher.rs
  crates/relayer-context/src/lib.rs
  crates/relayer-utils/src/lib.rs
  event-watchers/evm/src/lib.rs
  event-watchers/evm/src/open_vanchor/open_vanchor_deposit_handler.rs
  event-watchers/evm/src/open_vanchor/open_vanchor_leaves_handler.rs
  event-watchers/evm/src/signature_bridge_watcher.rs
  event-watchers/evm/src/vanchor/vanchor_deposit_handler.rs
  event-watchers/evm/src/vanchor/vanchor_encrypted_outputs_handler.rs
  event-watchers/evm/src/vanchor/vanchor_leaves_handler.rs
  services/block-poller/src/block_poller.rs
  services/webb-relayer/src/service/evm.rs
Labels: approved ✅

#497 bugfix: Custom Retry Policy for EVM providers
  Cargo.lock
  crates/relayer-context/Cargo.toml
  crates/relayer-context/src/ethers_retry_policy.rs
  crates/relayer-context/src/lib.rs
  crates/relayer-utils/src/probe.rs
  flake.lock
  flake.nix
  tests/lib/webbRelayer.ts
  tests/test/evm/invalidProviders.test.ts
Labels: p0 🔥, difficulty: medium 🚩

#375 Fees for substrate
  Cargo.lock
  README.md
  crates/relayer-handler-utils/src/lib.rs
  crates/relayer-handlers/src/lib.rs
  crates/tx-relay/Cargo.toml
  crates/tx-relay/src/evm/fees.rs
  crates/tx-relay/src/evm/vanchor.rs
  crates/tx-relay/src/lib.rs
  crates/tx-relay/src/substrate/fees.rs
  crates/tx-relay/src/substrate/mixer.rs
  crates/tx-relay/src/substrate/mod.rs
  crates/tx-relay/src/substrate/vanchor.rs
  services/webb-relayer/src/service/evm.rs
  services/webb-relayer/src/service/substrate.rs
  tests/lib/webbRelayer.ts
  tests/package.json
  tests/test/evm/RelayerTxTransfer.test.ts
  tests/test/evm/vanchorPrivateTransaction.test.ts
  tests/test/substrate/vanchorPrivateTransaction.test.ts
  tests/yarn.lock
Labels: p1 🟠, feature ➕, task ✔️, difficulty: medium 🚩, substrate

#517 Fix partial writes
  crates/relayer-store/src/lib.rs
  crates/relayer-store/src/mem.rs
  crates/relayer-store/src/sled.rs
  crates/relayer-utils/src/lib.rs
  event-watchers/evm/src/open_vanchor/open_vanchor_leaves_handler.rs
  event-watchers/evm/src/vanchor/vanchor_encrypted_outputs_handler.rs
  event-watchers/evm/src/vanchor/vanchor_leaves_handler.rs
  event-watchers/substrate/src/vanchor_encrypted_output_handler.rs
  event-watchers/substrate/src/vanchor_leaves_handler.rs
Labels: needs review 👓
