Repository webb-tools/relayer, pull requests merged in 2023-04, with the labels that each got.

#414 feat: Improve the `GasOracle` usage
  Cargo.lock
  Cargo.toml
  crates/relayer-config/src/lib.rs
  crates/relayer-context/src/lib.rs
  crates/relayer-utils/src/lib.rs
  crates/tx-relay/src/evm/fees.rs
  services/light-client-relayer/Cargo.toml
Labels: p0 🔥, feature ➕, needs review 👓

#471 fix: `u64` overflow when updating relayer metrics
  crates/relayer-utils/src/metric.rs
  crates/tx-relay/src/evm/mod.rs
Labels: approved ✅

#467 add proof-generation crate for masp integration
  Cargo.lock
  Cargo.toml
  crates/circom-proving/Cargo.toml
  crates/circom-proving/src/lib.rs
  crates/proof-generation/Cargo.toml
  crates/proof-generation/src/batch_prover.rs
  crates/proof-generation/src/lib.rs
  crates/proof-generation/src/proof_delegation.rs
  crates/proof-generation/src/types.rs
  crates/proof-generation/test_data/proofInputs.json
  tests/solidity-fixtures.dvc
Labels: needs review 👓

#477 Remove dynamic tx from relayer
  Cargo.lock
  crates/event-watcher-traits/Cargo.toml
  crates/event-watcher-traits/src/substrate/bridge_watcher.rs
  crates/proposal-signing-backends/src/dkg.rs
  crates/relayer-types/src/dynamic_payload.rs
  crates/relayer-types/src/lib.rs
  crates/tx-queue/src/substrate/substrate_tx_queue.rs
  event-watchers/substrate/src/signature_bridge_watcher.rs
  services/webb-relayer/src/service/mod.rs
  services/webb-relayer/src/service/substrate.rs
Labels: needs review 👓
